version: '3.4'

networks:
  dev:
    driver: bridge

services:
  frontend:
    image: first-app/fronted:latest
    container_name: frontend
    depends_on:
      - backend
    build:
      context: /First-App.WebUI
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    networks:
      - dev

  backend:
    container_name: backend
    image: first-app/backend:latest
    depends_on:
      - app_db
    restart: always
    build:
      context: /FirstApp
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=app_db;Port=5432;Database=First_App_Db;Pooling=true;
    networks:
      - dev

  app_db:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=First_App_Db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev
volumes:
  app_data: